### ISSUE TITLE
Failed to execute "git ls-remote --tags --heads git@github.ibm.com:WatsonAnalytics/wa-icons.git",

### ISSUE THREAD

**Issue by dealable** [IBM/watson-multimedia-analyzer#21]
CMD: bower install
PACKAGE: bower wa-icons#master
ERROR: ECMDERR Failed to execute "git ls-remote --tags --heads git@github.ibm.com:WatsonAnalytics/wa-icons.git", exit code of #128 Host key verification failed. fatal: Could not read from remote repository.  Please make sure you have the correct access rights and the repository exists.

**Comment by stevemart** [comment]
@rhagarty looks like there is a library we're installing that pulls in icons, but its behind our firewall, see line https://github.com/IBM/watson-multimedia-analyzer/blob/master/bower.json#L23 -- suggest we either import the icons we need and remove the dependency
