### ISSUE TITLE
you can delete this one - fixed the problem 

### ISSUE THREAD

**Issue by tal2k4xj** [IBM/watson-multimedia-analyzer#41]
For some reason I press "deploy to IBM Cloud" button, everything looks good and I open the URL and I see this :
![image](https://user-images.githubusercontent.com/11144416/44649481-b9d63780-a9ec-11e8-908a-4dd6c6f1448f.png)

**Comment by tal2k4xj** [comment]
sorry my bad .

**Comment by stevemart** [comment]
Closing per latest comment
